
belTestblog_accueil:
    path:      /{page}
    defaults:  { _controller: BelTestBlogBundle:Blog:index , page: 1 }
    requirements:
        page:  \d*
        
belTestblog_voir:
    path:      /article/{id}
    defaults:  { _controller: BelTestBlogBundle:Blog:voir }
     
belTestblog_ajouter:
    path:      /ajouter
    defaults:  { _controller: BelTestBlogBundle:Blog:ajouter }

belTestblog_modifier:
    path:      /modifier/{id}
    defaults:  { _controller: BelTestBlogBundle:Blog:modifier }
    requirements:
        id:  \d+
 
belTestblog_supprimer:
    path:      /supprimer/{id}
    defaults:  { _controller: BelTestBlogBundle:Blog:supprimer }
    requirements:
        id:  \d+
